export enum UserActionTypes {
	GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST',
	GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS',
	//
	GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS',
	SET_ERROR = 'SET_ERROR',
	ADD_PAGE = "ADD_PAGE",
	DECREMENT_PAGE = "DECREMENT_PAGE",
	INCREMENT_PAGE = "INCREMENT_PAGE"
}